### ISSUE TITLE
IndexError: invalid index to scalar variable.

### ISSUE THREAD

**Issue by ChouHuaZi** [wanghuanphd/MDvsFA_cGAN#9]
Traceback (most recent call last):
  File "D:\微信文件夹\WeChat Files\wxid_iknyrh9pnzs422\FileStorage\File\2023-03\pso_1.py", line 142, in <module>
    nn.train(case,label,a1,a2)
  File "D:\微信文件夹\WeChat Files\wxid_iknyrh9pnzs422\FileStorage\File\2023-03\bp.py", line 135, in train
    error += self.back_propagate(case, label, learn, correct)
  File "D:\微信文件夹\WeChat Files\wxid_iknyrh9pnzs422\FileStorage\File\2023-03\bp.py", line 99, in back_propagate
    error = label[o] - self.output_cells[o]
IndexError: invalid index to scalar variable.

**Comment by SuGuilin** [comment]
请问您是如何解决了，我也遇到同样的问题@ChouHuaZi


> Traceback (most recent call last): File "D:\微信文件夹\WeChat Files\wxid_iknyrh9pnzs422\FileStorage\File\2023-03\pso_1.py", line 142, in nn.train(case,label,a1,a2) File "D:\微信文件夹\WeChat Files\wxid_iknyrh9pnzs422\FileStorage\File\2023-03\bp.py", line 135, in train error += self.back_propagate(case, label, learn, correct) File "D:\微信文件夹\WeChat Files\wxid_iknyrh9pnzs422\FileStorage\File\2023-03\bp.py", line 99, in back_propagate error = label[o] - self.output_cells[o] IndexError: invalid index to scalar variable.
